---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: ["recipe[ganglia]", "recipe[minitest-handler]"]
  attributes: {
    "ganglia": {
        "server_addresses": [ "localhost" ]
    }, 
    "build_essential": {"compiletime" : false}
  }

- name: gmetad
  run_list: ["recipe[ganglia::gmetad]", "recipe[minitest-handler]"]
  attributes: {"build_essential": {"compiletime" : false}}

- name: web
  run_list: ["recipe[ganglia::web]", "recipe[minitest-handler]"]
  attributes: {"build_essential": {"compiletime" : false}}

- name: graphite 
  run_list: ["recipe[ganglia::graphite]", "recipe[minitest-handler]"]
  attributes: {"build_essential": {"compiletime" : false}} 

- name: server
  run_list: ["recipe[ganglia]", "recipe[ganglia::gmetad]", "recipe[ganglia::web]", "recipe[ganglia::graphite]", "recipe[minitest-handler]"]
  attributes: {"build_essential": {"compiletime" : false}}

